export const gender = [
  {
    id: "1",
    label: "Male",
    value: "Male",
  },
  {
    id: "2",
    label: "Female",
    value: "Female",
  },
];

export const Relationship = [
  {
    id: 1,
    label: "Single",
    value: "Single",
  },
  {
    id: 2,
    label: "In a relationship",
    value: "In a relationship",
  },
  {
    id: 3,
    label: "Enraged",
    value: "Enraged",
  },
  {
    id: 4,
    label: "Married",
    value: "Married",
  },
];

export const personCategory = [
  "Model",
  "Writer",
  "Actor",
  "Artist",
  "Singer",
  "Musician",
  "Influencer",
  "Blogger",
  "Photographer",
  "Doctor",
  "Engineer",
  "Politician",
  "Proshason",
  "Rab",
  "Makeup Artiste",
  "Army",
  "CID",
  "Pilot",
  "Technician",
  "Software Engineer",
  "Programmer",
  "Business man",
  "Founder",
  "C.E.O",
  "Owner",
  "Chairman",
  "It Expert",
];
export const companyCategory = [
  "Man Clothing",
  "Woman Clothing",
  "Baby Cloth",
  "Store",
  "Electric",
  "Makeup Artiste",
  "Home Made Food",
  "Organic Food",
  "Restaurant",
  "Fashion",
  "Watch",
  "jewlary",
  "Shoe",
  "Gold",
  "Computer",
  "Beauty Salon",
  "Internet Security",
  "Baby Store",
  "Magazine",
  "Panjibi",
  "Sari Store",
  "Company",
  "School",
  "University",
  "Private Company",
  "Advisement Agency",
  "Modeling Agency",
  "Fruit",
  "Madrasah",
  "Beauty Store",
  "Cosmetic",
  "Makeup",
];

export const topAnchors = [
  {
    id: 4,
    name: "Gina Rodriquez",
    amount: 12.75,
    icon: "../../public/icons/send-request.png",
  },
  {
    id: 6,
    name: "Javier Robertson",
    amount: 12.75,
    icon: "../../public/icons/user.png",
  },
  {
    id: 8,
    name: "Scarlett",
    amount: 12.75,
    icon: "../../public/icons/double-user.png",
  },
];
